[package]
name = "sealci"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.0"
tokio = { version = "1.38.0", features = ["full"] }
prost = "0.13.1"
prost-types = "0.13.1"
reqwest = "0.12.5"
futures = "0.3.30"
async-stream = "0.3.5"

[build-dependencies]
tonic-build = "0.12.0"
