configurations:
  - event: "*"
    repo_owner: "baptistebronsin"
    repo_name: "test-sealci"
    pipeline_name: "test-sealci"
    github_token: "github-token"
    actions_path: "./actions/actions.yaml"
  - event: "commit"
    repo_owner: "baptistebronsin"
    repo_name: "test-sealci"
    pipeline_name: "test-sealci"
    github_token: "github-token"
    actions_path: "./actions/actions.yaml"


